# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: webmailapp_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webmailapp_net
    ports:
      - "5432:5432"
    restart: unless-stopped

  postfix:
    build:
      context: ./postfix
      dockerfile: Dockerfile
    container_name: webmailapp_postfix
    environment:
      MAIL_DB_HOST: ${MAIL_DB_HOST}
      MAIL_DB_USER: ${MAIL_DB_USER}
      MAIL_DB_PASSWORD: ${MAIL_DB_PASSWORD}
      MAIL_DB_NAME: ${MAIL_DB_NAME}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      VMAIL_UID: ${VMAIL_UID}
      VMAIL_GID: ${VMAIL_GID}
    volumes:
      - maildata:/var/mail/vhosts
      - ./scripts:/scripts
    depends_on:
      - postgres
    networks:
      - webmailapp_net
    ports:
      - "2525:25"
    restart: unless-stopped
    env_file:
      - .env

  dovecot:
    build:
      context: ./dovecot
      dockerfile: Dockerfile
    container_name: webmailapp_dovecot
    environment:
      MAIL_DB_HOST: ${MAIL_DB_HOST}
      MAIL_DB_USER: ${MAIL_DB_USER}
      MAIL_DB_PASSWORD: ${MAIL_DB_PASSWORD}
      MAIL_DB_NAME: ${MAIL_DB_NAME}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      VMAIL_UID: ${VMAIL_UID}
      VMAIL_GID: ${VMAIL_GID}
    volumes:
      - maildata:/var/mail/vhosts
    depends_on:
      - postgres
    networks:
      - webmailapp_net
    ports:
      - "1143:143"
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: webmailapp_backend
    # volumes:
    #   - ../backend:/app # Mount local backend code
    #   - /app/node_modules # Keep container's node_modules separate
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      IMAP_HOST: ${IMAP_HOST}
      IMAP_PORT: ${IMAP_PORT}
      NODE_ENV: development
    depends_on:
      - postgres
      - postfix
      - dovecot
    networks:
      - webmailapp_net
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: webmailapp_frontend
    environment:
      VITE_API_URL: http://localhost:3001
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      - backend
    networks:
      - webmailapp_net
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  maildata:
    driver: local

networks:
  webmailapp_net:
    driver: bridge
